INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001001','MMR001','Myitkyina','မြစ်ကြီးနား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001002','MMR001','Waingmaw','ဝိုင်းမော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001003','MMR001','Injangyang','အင်ဂျန်းယန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001004','MMR001','Tanai','တနိုင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001005','MMR001','Chipwi','ချီဗွေ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001006','MMR001','Tsawlaw','ဆော့လော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001007','MMR001','Mohnyin','မိုးညှင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001008','MMR001','Mogaung','မိုးကောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001009','MMR001','Hpakant','ဖားကန့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001010','MMR001','Bhamo','ဗန်းမော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001011','MMR001','Shwegu','ရွှေကူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001012','MMR001','Momauk','မိုးမောက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001013','MMR001','Mansi','မန်စီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001014','MMR001','Puta-O','ပူတာအို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001015','MMR001','Sumprabum','ဆွမ်ပရာဘွမ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001016','MMR001','Machanbaw','မချမ်းဘော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001017','MMR001','Nawngmun','နောင်မွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR001018','MMR001','Khaunglanhpu','ခေါင်လန်ဖူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002001','MMR002','Loikaw','လွိုင်ကော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002002','MMR002','Demoso','ဒီမောဆို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002003','MMR002','Hpruso','ဖရူဆို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002004','MMR002','Shadaw','ရှားတော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002005','MMR002','Bawlake','ဘောလခဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002006','MMR002','Hpasawng','ဖားဆောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR002007','MMR002','Mese','မယ်စဲ့',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003001','MMR003','Hpa-An','ဘားအံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003002','MMR003','Hlaingbwe','လှိုင်းဘွဲ့',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003003','MMR003','Hpapun','ဖာပွန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003004','MMR003','Thandaunggyi','သံတောင်ကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003005','MMR003','Myawaddy','မြဝတီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003006','MMR003','Kawkareik','ကော့ကရိတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR003007','MMR003','Kyainseikgyi','ကြာအင်းဆိပ်ကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004001','MMR004','Falam','ဖလမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004002','MMR004','Hakha','ဟားခါး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004003','MMR004','Thantlang','ထန်တလန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004004','MMR004','Tedim','တီးတိန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004005','MMR004','Tonzang','တွန်းဇံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004006','MMR004','Mindat','မင်းတပ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004007','MMR004','Matupi','မတူပီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004008','MMR004','Kanpetlet','ကန်ပက်လက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR004009','MMR004','Paletwa','ပလက်ဝ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005001','MMR005','Sagaing','စစ်ကိုင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005002','MMR005','Myinmu','မြင်းမူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005003','MMR005','Myaung','မြောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005004','MMR005','Shwebo','ရွှေဘို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005005','MMR005','Khin-U','ခင်ဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005006','MMR005','Wetlet','ဝက်လက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005007','MMR005','Kanbalu','ကန့်ဘလူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005008','MMR005','Kyunhla','ကျွန်းလှ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005009','MMR005','Ye-U','ရေဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005010','MMR005','Tabayin','ဒီပဲယင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005011','MMR005','Taze','တန့်ဆည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005012','MMR005','Monywa','မုံရွာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005013','MMR005','Budalin','ဘုတလင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005014','MMR005','Ayadaw','အရာတော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005015','MMR005','Chaung-U','ချောင်းဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005016','MMR005','Yinmarbin','ယင်းမာပင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005017','MMR005','Kani','ကနီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005018','MMR005','Salingyi','ဆားလင်းကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005019','MMR005','Pale','ပုလဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005020','MMR005','Katha','ကသာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005021','MMR005','Indaw','အင်းတော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005022','MMR005','Tigyaing','ထီးချိုင့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005023','MMR005','Banmauk','ဗန်းမောက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005024','MMR005','Kawlin','ကောလင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005025','MMR005','Wuntho','ဝန်းသို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005026','MMR005','Pinlebu','ပင်လည်ဘူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005027','MMR005','Kale','ကလေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005028','MMR005','Kalewa','ကလေးဝ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005029','MMR005','Mingin','မင်းကင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005030','MMR005','Tamu','တမူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005031','MMR005','Mawlaik','မော်လိုက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005032','MMR005','Paungbyin','ဖေါင်းပြင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005033','MMR005','Hkamti','ခန္တီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005034','MMR005','Homalin','ဟုမ္မလင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005035','MMR005','Lay Shi','လေရှီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005036','MMR005','Lahe','လဟယ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR005037','MMR005','Nanyun','နန်းယွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006001','MMR006','Dawei','ထားဝယ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006002','MMR006','Launglon','လောင်းလုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006003','MMR006','Thayetchaung','သရက်ချောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006004','MMR006','Yebyu','ရေဖြူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006005','MMR006','Myeik','မြိတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006006','MMR006','Kyunsu','ကျွန်းစု',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006007','MMR006','Palaw','ပုလော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006008','MMR006','Tanintharyi','တနင်္သာရီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006009','MMR006','Kawthoung','ကော့သောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR006010','MMR006','Bokpyin','ဘုတ်ပြင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007001','MMR111','Bago','ပဲခူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007002','MMR111','Thanatpin','သနပ်ပင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007003','MMR111','Kawa','ကဝ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007004','MMR111','Waw','ဝေါ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007005','MMR111','Nyaunglebin','ညောင်လေးပင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007006','MMR111','Kyauktaga','ကျောက်တံခါး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007007','MMR111','Daik-U','ဒိုက်ဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007008','MMR111','Shwegyin','ရွှေကျင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007009','MMR111','Taungoo','တောင်ငူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007010','MMR111','Yedashe','ရေတာရှည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007011','MMR111','Kyaukkyi','ကျောက်ကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007012','MMR111','Phyu','ဖြူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007013','MMR111','Oktwin','အုတ်တွင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR007014','MMR111','Htantabin','ထန်းတပင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008001','MMR111','Pyay','ပြည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008002','MMR111','Paukkhaung','ပေါက်ခေါင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008003','MMR111','Padaung','ပန်းတောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008004','MMR111','Paungde','ပေါင်းတည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008005','MMR111','Thegon','သဲကုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008006','MMR111','Shwedaung','ရွှေတောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008007','MMR111','Thayarwady','သာယာဝတီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008008','MMR111','Letpadan','လက်ပံတန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008009','MMR111','Minhla','မင်းလှ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008010','MMR111','Okpho','အုတ်ဖို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008011','MMR111','Zigon','ဇီးကုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008012','MMR111','Nattalin','နတ္တလင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008013','MMR111','Monyo','မိုးညို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR008014','MMR111','Gyobingauk','ကြို့ပင်ကောက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009001','MMR009','Magway','မကွေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009002','MMR009','Yenangyaung','ရေနံချောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009003','MMR009','Chauk','ချောက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009004','MMR009','Taungdwingyi','တောင်တွင်းကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009005','MMR009','Myothit','မြို့သစ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009006','MMR009','Natmauk','နတ်မောက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009007','MMR009','Minbu','မင်းဘူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009008','MMR009','Pwintbyu','ပွင့်ဖြူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009009','MMR009','Ngape','ငဖဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009010','MMR009','Salin','စလင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009011','MMR009','Sidoktaya','စေတုတ္တရာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009012','MMR009','Thayet','သရက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009013','MMR009','Minhla','မင်းလှ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009014','MMR009','Mindon','မင်းတုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009015','MMR009','Kamma','ကံမ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009016','MMR009','Aunglan','အောင်လံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009017','MMR009','Sinbaungwe','ဆင်ပေါင်ဝဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009018','MMR009','Pakokku','ပခုက္ကူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009019','MMR009','Yesagyo','ရေစကြို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009020','MMR009','Myaing','မြိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009021','MMR009','Pauk','ပေါက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009022','MMR009','Seikphyu','ဆိပ်ဖြူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009023','MMR009','Gangaw','ဂန့်ဂေါ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009024','MMR009','Tilin','ထီးလင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR009025','MMR009','Saw','ဆော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010001','MMR010','Aungmyaythazan','အောင်မြေသာဇံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010002','MMR010','Chanayethazan','ချမ်းအေးသာဇံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010003','MMR010','Mahaaungmyay','မဟာအောင်မြေ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010004','MMR010','Chanmyathazi','ချမ်းမြသာစည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010005','MMR010','Pyigyitagon','ပြည်ကြီးတံခွန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010006','MMR010','Amarapura','အမရပူရ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010007','MMR010','Patheingyi','ပုသိမ်ကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010008','MMR010','Pyinoolwin','ပြင်ဦးလွင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010009','MMR010','Madaya','မတ္တရာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010010','MMR010','Singu','စဉ့်ကူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010011','MMR010','Mogoke','မိုးကုတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010012','MMR010','Thabeikkyin','သပိတ်ကျဉ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010013','MMR010','Kyaukse','ကျောက်ဆည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010014','MMR010','Sintgaing','စဉ့်ကိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010015','MMR010','Myittha','မြစ်သား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010016','MMR010','Tada-U','တံတားဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010017','MMR010','Myingyan','မြင်းခြံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010018','MMR010','Taungtha','တောင်သာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010019','MMR010','Natogyi','နွားထိုးကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010020','MMR010','Kyaukpadaung','ကျောက်ပန်းတောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010021','MMR010','Ngazun','ငါန်းဇွန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010022','MMR010','Nyaung-U','ညောင်ဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010023','MMR010','Yamethin','ရမည်းသင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010024','MMR010','Pyawbwe','ပျော်ဘွယ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010028','MMR010','Meiktila','မိတ္ထီလာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010029','MMR010','Mahlaing','မလှိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010030','MMR010','Thazi','သာစည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR010031','MMR010','Wundwin','ဝမ်းတွင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011001','MMR011','Mawlamyine','မော်လမြိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011002','MMR011','Kyaikmaraw','ကျိုက္မရော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011003','MMR011','Chaungzon','ချောင်းဆုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011004','MMR011','Thanbyuzayat','သံဖြူဇရပ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011005','MMR011','Mudon','မုဒုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011006','MMR011','Ye','ရေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011007','MMR011','Thaton','သထုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011008','MMR011','Paung','ပေါင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011009','MMR011','Kyaikto','ကျိုက်ထို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR011010','MMR011','Bilin','ဘီးလင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012001','MMR012','Sittwe','စစ်တွေ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012002','MMR012','Ponnagyun','ပုဏ္ဏားကျွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012003','MMR012','Mrauk-U','မြောက်ဦး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012004','MMR012','Kyauktaw','ကျောက်တော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012005','MMR012','Minbya','မင်းပြား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012006','MMR012','Myebon','မြေပုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012007','MMR012','Pauktaw','ပေါက်တော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012008','MMR012','Rathedaung','ရသေ့တောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012009','MMR012','Maungdaw','မောင်တော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012010','MMR012','Buthidaung','ဘူးသီးတောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012011','MMR012','Kyaukpyu','ကျောက်ဖြူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012012','MMR012','Munaung','မာန်အောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012013','MMR012','Ramree','ရမ်းဗြဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012014','MMR012','Ann','အမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012015','MMR012','Thandwe','သံတွဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012016','MMR012','Toungup','တောင်ကုတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR012017','MMR012','Gwa','ဂွ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013001','MMR013','Insein','အင်းစိန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013002','MMR013','Mingaladon','မင်္ဂလာဒုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013003','MMR013','Hmawbi','မှော်ဘီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013004','MMR013','Hlegu','လှည်းကူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013005','MMR013','Taikkyi','တိုက်ကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013006','MMR013','Htantabin','ထန်းတပင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013007','MMR013','Shwepyithar','ရွှေပြည်သာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013008','MMR013','Hlaingtharya','လှိုင်သာယာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013009','MMR013','Thingangyun','သင်္ဃန်းကျွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013010','MMR013','Yankin','ရန်ကင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013011','MMR013','South Okkalapa','တောင်ဥက္ကလာပ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013012','MMR013','North Okkalapa','မြောက်ဥက္ကလာပ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013013','MMR013','Thaketa','သာကေတ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013014','MMR013','Dawbon','ဒေါပုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013015','MMR013','Tamwe','တာမွေ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013016','MMR013','Pazundaung','ပုဇွန်တောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013017','MMR013','Botahtaung','ဗိုလ်တထောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013018','MMR013','Dagon Myothit (South)','ဒဂုံမြို့သစ်တောင်ပိုင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013019','MMR013','Dagon Myothit (North)','ဒဂုံမြို့သစ်မြောက်ပိုင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013020','MMR013','Dagon Myothit (East)','ဒဂုံမြို့သစ်အရှေ့ပိုင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013021','MMR013','Dagon Myothit (Seikkan)','ဒဂုံမြို့သစ်ဆိပ်ကမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013022','MMR013','Mingalartaungnyunt','မင်္ဂလာတောင်ညွန့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013023','MMR013','Thanlyin','သန်လျှင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013024','MMR013','Kyauktan','ကျောက်တန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013025','MMR013','Thongwa','သုံးခွ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013026','MMR013','Kayan','ခရမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013027','MMR013','Twantay','တွံတေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013028','MMR013','Kawhmu','ကော့မှုး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013029','MMR013','Kungyangon','ကွမ်းခြံကုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013030','MMR013','Dala','ဒလ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013031','MMR013','Seikgyikanaungto','ဆိပ်ကြီးခနောင်တို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013032','MMR013','Cocokyun','ကိုကိုးကျွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013033','MMR013','Kyauktada','ကျောက်တံတား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013034','MMR013','Pabedan','ပန်းပဲတန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013035','MMR013','Lanmadaw','လမ်းမတော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013036','MMR013','Latha','လသာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013037','MMR013','Ahlone','အလုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013038','MMR013','Kyeemyindaing','ကြည့်မြင်တိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013039','MMR013','Sanchaung','စမ်းချောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013040','MMR013','Hlaing','လှိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013041','MMR013','Kamaryut','ကမာရွတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013042','MMR013','Mayangone','မရမ်းကုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013043','MMR013','Dagon','ဒဂုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013044','MMR013','Bahan','ဗဟန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR013045','MMR013','Seikkan','ဆိပ်ကမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014001','MMR222','Taunggyi','တောင်ကြီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014002','MMR222','Nyaungshwe','ညောင်ရွှေ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014003','MMR222','Hopong','ဟိုပုံး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014004','MMR222','Hsihseng','ဆီဆိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014005','MMR222','Kalaw','ကလော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014006','MMR222','Pindaya','ပင်းတယ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014007','MMR222','Ywangan','ရွာငံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014008','MMR222','Lawksawk','ရပ်စောက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014009','MMR222','Pinlaung','ပင်လောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014010','MMR222','Pekon','ဖယ်ခုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014011','MMR222','Loilen','လွိုင်လင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014012','MMR222','Laihka','လဲချား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014013','MMR222','Nansang','နမ့်စန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014014','MMR222','Kunhing','ကွန်ဟိန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014015','MMR222','Kyethi','ကျေးသီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014016','MMR222','Mongkaing','မိုင်းကိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014017','MMR222','Monghsu','မိုင်းရှုး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014018','MMR222','Langkho','လင်းခေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014019','MMR222','Mongnai','မိုးနဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014020','MMR222','Mawkmai','မောက်မယ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR014021','MMR222','Mongpan','မိုင်းပန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015001','MMR222','Lashio','လားရှိုး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015002','MMR222','Hseni','သိန်းနီ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015003','MMR222','Mongyai','မိုင်းရယ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015004','MMR222','Tangyan','တန့်ယန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015005','MMR222','Pangsang','ပန်ဆန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015006','MMR222','Narphan','နားဖန့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015007','MMR222','Pangwaun','ပန်ဝိုင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015008','MMR222','Mongmao','မိုင်းမော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015009','MMR222','Muse','မူဆယ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015010','MMR222','Namhkan','နမ့်ခမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015011','MMR222','Kutkai','ကွတ်ခိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015012','MMR222','Kyaukme','ကျောက်မဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015013','MMR222','Nawnghkio','နောင်ချို',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015014','MMR222','Hsipaw','သီပေါ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015015','MMR222','Namtu','နမ္မတူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015016','MMR222','Namhsan','နမ့်ဆန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015017','MMR222','Mongmit','မိုးမိတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015018','MMR222','Mabein','မဘိမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015019','MMR222','Manton','မန်တုန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015020','MMR222','Kunlong','ကွမ်းလုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015021','MMR222','Hopang','ဟိုပန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015022','MMR222','Laukkaing','လောက်ကိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015023','MMR222','Konkyan','ကုန်းကြမ်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015024','MMR222','Matman','မက်မန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015201','MMR222','Konkyan (Kokang SAZ)','ကုန်းကြမ်း (အထူးဒေသ ၁)',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015202','MMR222','Laukkaing (Kokang SAZ)','လောက်ကိုင် (အထူးဒေသ ၁)',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015203','MMR222','Chinshwehaw Sub-township (Kokang SAZ)','ချင်းရွှေဟော်မြို့နယ်ခွဲ (အထူးဒေသ ၁)',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015301','MMR222','Nam Tit','နမ့် တစ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015302','MMR222','Nar Wee (Na Wi)','နာဝီး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015303','MMR222','Man Tun','မန်တွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015304','MMR222','Kawng Min Hsang','ကောင်မင်ဆန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015305','MMR222','Hsawng Hpa (Saun Pha)','ဆောင်ဖ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015306','MMR222','Hkun Mar (Hkwin Ma)','ခွန်းမား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015307','MMR222','Long Htan','လုံထန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015308','MMR222','Yawng Lin','ယောင်လင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015309','MMR222','Lin Haw','လင်ဟော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015310','MMR222','Ka Lawng Hpar','ကလောင်ဖါ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015311','MMR222','Aik Chan (Ai\' Chun)','အိုက်ချန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015312','MMR222','Yin Pang','ရင်ဖန့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015313','MMR222','Man Man Hseng','မန်မန်ဆိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015314','MMR222','Nawng Hkit','နောင်ခစ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015315','MMR222','Nam Hkam Wu','နမ်ခမ်းဝူး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015316','MMR222','Nar Kawng','နားကောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015317','MMR222','Pang Hkam','ပန်ခမ့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR015318','MMR222','Pang Yang','ပန်ယန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016001','MMR222','Kengtung','ကျိုင်းတုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016002','MMR222','Mongkhet','မိုင်းခတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016003','MMR222','Mongyang','မိုင်းယန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016005','MMR222','Mongla','မိုင်းလား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016006','MMR222','Monghsat','မိုင်းဆတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016007','MMR222','Mongping','မိုင်းပျင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016008','MMR222','Mongton','မိုင်းတုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016009','MMR222','Tachileik','တာချီလိတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016010','MMR222','Monghpyak','မိုင်းဖြတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016011','MMR222','Mongyawng','မိုင်းယောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016319','MMR222','Mong Hpen','မိုင်းဖျန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016320','MMR222','Ho Tawng (Ho Tao)','ဟိုတောင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016321','MMR222','Mong Pawk','မိုင်းပေါက်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016322','MMR222','Mong Kar','မိုင်းကာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR016323','MMR222','Nam Hpai','နမ့်ဖိုင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017001','MMR017','Pathein','ပုသိမ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017002','MMR017','Kangyidaunt','ကန်ကြီးထောင့်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017003','MMR017','Thabaung','သာပေါင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017004','MMR017','Ngapudaw','ငပုတော',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017005','MMR017','Kyonpyaw','ကျုံပျော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017006','MMR017','Yegyi','ရေကြည်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017007','MMR017','Kyaunggon','ကျောင်းကုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017008','MMR017','Hinthada','ဟင်္သာတ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017009','MMR017','Zalun','ဇလွန်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017010','MMR017','Lemyethna','လေးမျက်နှာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017011','MMR017','Myanaung','မြန်အောင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017012','MMR017','Kyangin','ကြံခင်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017013','MMR017','Ingapu','အင်္ဂပူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017014','MMR017','Myaungmya','မြောင်းမြ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017015','MMR017','Einme','အိမ္မဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017016','MMR017','Labutta','လပွတ္တာ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017017','MMR017','Wakema','ဝါးခယ်မ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017018','MMR017','Mawlamyinegyun','မော်လမြိုင်ကျွန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017019','MMR017','Maubin','မအူပင်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017020','MMR017','Pantanaw','ပန်းတနော်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017021','MMR017','Nyaungdon','ညောင်တုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017022','MMR017','Danubyu','ဓနုဖြူ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017023','MMR017','Pyapon','ဖျာပုံ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017024','MMR017','Bogale','ဘိုကလေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017025','MMR017','Kyaiklat','ကျိုက်လတ်',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR017026','MMR017','Dedaye','ဒေးဒရဲ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018001','MMR018','Zay Yar Thi Ri','ဇေယျာသီရိ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018002','MMR018','Za Bu Thi Ri','ဇမ္ဗူသီရိ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018003','MMR018','Tatkon','တပ်ကုန်း',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018004','MMR018','Det Khi Na Thi Ri','ဒက္ခိဏသီရိ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018005','MMR018','Poke Ba Thi Ri','ပုဗ္ဗသီရိ',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018006','MMR018','Pyinmana','ပျဉ်းမနား',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018007','MMR018','Lewe','လယ်ဝေး',0,1);
INSERT INTO townships (`code`,`state_code`,`township_name_en`,`township_name_mm`,`postal_code`,`is_active`) VALUES ('MMR018008','MMR018','Oke Ta Ra Thi Ri','ဥတ္တရသီရိ',0,1);
