package models

const (
	AccountCodeAccountsReceivable        = "100"
	AccountCodeAdvanceTax                = "101"
	AccountCodeEmployeeAdvance           = "102"
	AccountCodeFinishedGoods             = "103"
	AccountCodeFunitureAndEquipment      = "104"
	AccountCodeGoodsInTransit            = "105"
	AccountCodeInventoryAsset            = "106"
	AccountCodePettyCash                 = "107"
	AccountCodeSalesToCustomer           = "108"
	AccountCodeUndepositedFunds          = "109"
	AccountCodeWorkInProgress            = "110"
	AccountCodeAdvancePayment            = "111"
	AccountCodeGoodsInTransfer           = "112"
	AccountCodeAccountsPayable           = "200"
	AccountCodeTaxPayable                = "201"
	AccountCodeUnearnedRevenue           = "202"
	AccountCodeOpeningBalanceAdjustments = "203"
	AccountCodeEmployeeReimbursements    = "204"
	AccountCodeDimensionAdjustments      = "205"
	AccountCodeInterBranchAccount        = "206"
	AccountCodeRetainedEarnings          = "300"
	AccountCodeOwnerEquity               = "301"
	AccountCodeOpeningBalanceOffset      = "302"
	AccountCodeDrawings                  = "303"
	AccountCodeOtherCharges              = "400"
	AccountCodeSales                     = "401"
	AccountCodeGeneralIncome             = "402"
	AccountCodeInterestIncome            = "403"
	AccountCodeLateFeeIncome             = "404"
	AccountCodePurchaseDiscount          = "405"
	AccountCodeShippingCharge            = "406"
	AccountCodeLodging                   = "500"
	AccountCodeBankFeesAndCharges        = "501"
	AccountCodeExchangeGainOrLoss        = "502"
	AccountCodeBadDebt                   = "503"
	AccountCodeUncategorized             = "504"
	AccountCodeOtherExpenses             = "505"
	AccountCodeCostOfGoodsSold           = "506"
	AccountCodeDiscount                  = "507"
	AccountCodeParking                   = "508"
)

func GetDefaultModules() map[string]string {
	defaultModules := map[string]string{
		"Account": "create;update;delete;read",
		//
		// "Accounting":                  "reconcile",
		"AccountJournalTransactions":   "read",
		"AccountTransactionReport":     "read",
		"AccountTypeSummaryReport":     "read",
		"APAgingDetailReport":          "read",
		"APAgingSummaryReport":         "read",
		"ARAgingDetailReport":          "read",
		"ARAgingSummaryReport":         "read",
		"Attachment":                   "upload;remove",
		"AvailableStocks":              "read",
		"BalanceSheetReport":           "read",
		"BankingAccount":               "read",
		"BankingTransaction":           "create;update;delete;read",
		"Bill":                         "create;update;delete;read",
		"BillDetailReport":             "read",
		"Branch":                       "create;update;delete;read",
		"Business":                     "read;update",
		"CashFlowReport":               "read",
		"ClosingInventory":             "read",
		"Comment":                      "create;delete",
		"CreditNote":                   "create;update;delete;read",
		"CreditNoteDetailsReport":      "read",
		"Currency":                     "create;update;delete;read",
		"CustomerApplyCredit":          "create",
		"CustomerApplyToInvoice":       "create",
		"CustomerBalancesReport":       "read",
		"CustomerBalanceSummaryReport": "read",
		"Customer":                     "create;update;delete;read",
		"CustomerCreditInvoice":        "delete",
		"CustomerPayment":              "create;update;delete;read",
		"CustomerRefundHistoryReport":  "read",
		"DeliveryMethod":               "create;update;delete;read",
		"DetailedGeneralLedgerReport":  "read",
		"Document":                     "read",
		"Expense":                      "create;update;delete;read",
		"ExpenseByCategory":            "read",
		"ExpenseDetailReport":          "read",
		"ExpenseSummaryByCategory":     "read",
		"File":                         "upload;remove",
		"GeneralLedgerReport":          "read",
		// "History":                          "read", listHistory is allowed by default
		// "History": "delete"
		"Image":                           "upload;remove",
		"InventoryAdjustment":             "create;delete;read",
		"InventorySummaryReport":          "read",
		"InventoryValuation":              "read",
		"InventoryValuationSummaryReport": "read",
		"Journal":                         "create;update;delete;read",
		"JournalReport":                   "read",
		"Module":                          "read",
		"MoneyAccount":                    "create;update;delete;read",
		"MovementOfEquityReport":          "read",
		"OpeningBalance":                  "read;update",
		"OpeningBalanceDetails":           "read",
		"OpeningStockGroup":               "create",
		"PayableDetailReport":             "read",
		"PayableSummaryReport":            "read",
		"PaymentMode":                     "create;update;delete;read",
		"PaymentsMade":                    "read",
		"PaymentsReceived":                "read",
		"PosInvoicePayment":               "create",
		"ProductCategory":                 "create;update;delete;read",
		"Product":                         "create;update;delete;read",
		"ProductGroup":                    "create;update;delete;read",
		"ProductModifier":                 "create;update;delete;read",
		"ProductSalesReport":              "read",
		"ProductTransactions":             "read",
		"ProductUnit":                     "create;update;delete;read",
		"ProductVariant":                  "create;update;delete;read",
		"ProfitAndLossReport":             "read",
		"PurchaseOrder":                   "create;update;delete;read",
		"PurchaseOrderDetailReport":       "read",
		"PurchasesByProductReport":        "read",
		"PurchasesBySupplierReport":       "read",
		"Reason":                          "create;update;delete;read",
		"ReceivableDetailReport":          "read",
		"ReceivableSummaryReport":         "read",
		"RecurringBill":                   "create;update;delete;read",
		"Refund":                          "create;update;delete",
		"Role":                            "create;update;delete;read",
		"RoleModule":                      "update;delete;read",
		"SalesByCustomerReport":           "read",
		"SalesByProductReport":            "read",
		"SalesBySalesPersonReport":        "read",
		"SalesInvoice":                    "create;update;delete;read",
		"SalesInvoiceDetailReport":        "read",
		"SalesOrder":                      "create;update;delete;read",
		"SalesOrderDetailReport":          "read",
		"SalesPerson":                     "create;update;delete;read",
		"ShipmentPreference":              "create;update;delete;read",
		"State":                           "read",
		"StockSummaryReport":              "read",
		"SupplierApplyCredit":             "create",
		"SupplierApplyToBill":             "create",
		"Supplier":                        "create;update;delete;read",
		"SupplierBalancesReport":          "read",
		"SupplierBalanceSummaryReport":    "read",
		"SupplierCreditBill":              "delete",
		"SupplierCredit":                  "create;update;delete;read",
		"SupplierCreditDetailsReport":     "read",
		"SupplierPayment":                 "create;update;delete;read",
		"SupplierRefundHistoryReport":     "read",
		"Tax":                             "create;update;delete;read",
		"TaxGroup":                        "create;update;delete;read",
		"TaxSetting":                      "update",
		"TopExpense":                      "read",
		"TotalCashFlow":                   "read",
		"TotalIncomeExpense":              "read",
		"TotalPayableReceivable":          "read",
		"Township":                        "read",
		"TransactionLocking":              "update",
		"TransactionLockingRecord":        "read",
		"TransactionNumberSeries":         "create;update;delete;read",
		"TransferOrder":                   "create;read",
		"TrialBalanceReport":              "read",
		"UnusedCustomerCreditAdvances":    "read",
		"UnusedCustomerCredits":           "read",
		"UnusedSupplierCreditAdvances":    "read",
		"UnusedSupplierCredits":           "read",
		"UserAccount":                     "create;update;delete;read",
		// "User":                             "create;update;delete;read",
		"Warehouse":                        "create;update;delete;read",
		"WarehouseInventoryReport":         "read",
		"UnrealisedExchangeGainLossReport": "read",
		"RealisedExchangeGainLossReport":   "read",
	}
	return defaultModules
}

func GetDefaultAllowedPaths() map[string]bool {
	return map[string]bool{
		// Document fetch is used widely for attachments; authorization is enforced server-side.
		"getDocument":               true,
		"listAllAccount":            true,
		"listAllBranch":             true,
		"listAllCurrency":           true,
		"listAllTax":                true,
		"listAllTaxGroup":           true,
		"listAllState":              true,
		"listAllTownship":           true,
		"listAllWarehouse":          true,
		"listAllProduct":            true,
		"listAllProductVariant":     true,
		"listAllProductUnit":        true,
		"listAllProductCategory":    true,
		"listAllShipmentPreference": true,
		"listAllPaymentMode":        true,
		"listAllReason":             true,
		"listAllDeliveryMethod":     true,
		"listAllSalesPerson":        true,
		"getBusiness":               true,
		"clearRedis":                true,
		"changePassword":            true,
		"logout":                    true,
		"getHistory":                true,
		"listHistory":               true,
		"getComment":                true,
		"listComment":               true,
		// Product details page uses this query; it still requires @auth (logged-in user),
		// but should not be blocked by role-path mapping.
		"getWarehouseInventoryByProduct": true,
	}
}

func GetAdminPaths() map[string]bool {
	return map[string]bool{
		"createModule":         true,
		"updateModule":         true,
		"deleteModule":         true,
		"listModules":          true,
		"getRole":              true,
		"listRole":             true,
		"createUser":           true,
		"deleteUser":           true,
		"getUser":              true,
		"listUser":             true,
		"resetPasswordUser":    true,
		"toggleActiveUser":     true,
		"createBusiness":       true,
		"toggleActiveBusiness": true,
		"getBusinessAdmin":     true,
		"listAllBusiness":      true,
		"createState":          true,
		"updateState":          true,
		"toggleActiveState":    true,
		"getState":             true,
		"listState":            true,
		"listAllState":         true,
		"paginateState":        true,
		"createTownship":       true,
		"updateTownship":       true,
		"toggleActiveTownship": true,
		"getTownship":          true,
		"listTownship":         true,
		"listAllTownship":      true,
		"paginateTownship":     true,
		"paginateHistory":      true,
		"clearRedis":           true,
		"reconcileAccounting":  true,
		"register":             true,
	}

}

func GetQueryPrefixMap() map[string][]string {
	return map[string][]string{
		"APAgingDetailReport|read":          {"get"},
		"APAgingSummaryReport|read":         {"get"},
		"ARAgingDetailReport|read":          {"get"},
		"ARAgingSummaryReport|read":         {"get"},
		"Account|read":                      {"get", "list", "listAll"},
		"AccountJournalTransactions|read":   {"get"},
		"AccountTransactionReport|read":     {"paginate", "getAll"},
		"AccountTypeSummaryReport|read":     {"get"},
		"AvailableStocks|read":              {"get"},
		"BalanceSheetReport|read":           {"get"},
		"BankingAccount|read":               {"list"},
		"BankingTransaction|read":           {"get", "paginate"},
		"Bill|read":                         {"get", "paginate"},
		"BillDetailReport|read":             {"get"},
		"Branch|read":                       {"get", "list", "listAll"},
		"Business|read":                     {"get", "listAll"},
		"BusinessAdmin|read":                {"get"},
		"CashFlowReport|read":               {"get"},
		"ClosingInventory|read":             {"get"},
		"Comment|read":                      {"get", "list"},
		"CreditNote|read":                   {"get", "paginate"},
		"CreditNoteDetailsReport|read":      {"get"},
		"Currency|read":                     {"get", "list", "listAll"},
		"Customer|read":                     {"get", "list", "paginate"},
		"CustomerBalanceSummaryReport|read": {"get"},
		"CustomerBalancesReport|read":       {"get"},
		"CustomerPayment|read":              {"get", "paginate"},
		"CustomerRefundHistoryReport|read":  {"get"},
		"DeliveryMethod|read":               {"get", "list", "listAll"},
		"DetailedGeneralLedgerReport|read":  {"paginate", "getAll"},
		"Document|read":                     {"get"},
		"Expense|read":                      {"get", "paginate"},
		"ExpenseByCategory|read":            {"get"},
		"ExpenseDetailReport|read":          {"get"},
		"ExpenseSummaryByCategory|read":     {"get"},
		"GeneralLedgerReport|read":          {"get"},
		// "History|read":                          {"get", "list", "paginate"},
		"InventoryAdjustment|read":              {"get", "paginate"},
		"InventorySummaryReport|read":           {"get"},
		"InventoryValuation|read":               {"get"},
		"InventoryValuationSummaryReport|read":  {"get"},
		"Journal|read":                          {"get", "paginate"},
		"JournalReport|read":                    {"paginate", "getAll"},
		"Module|read":                           {"get", "list"},
		"MoneyAccount|read":                     {"get", "list", "listAll", "paginate"},
		"MovementOfEquityReport|read":           {"get"},
		"OpeningBalance|read":                   {"get"},
		"OpeningBalanceDetails|read":            {"getPayable", "getReceivable", "getStock"},
		"PayableDetailReport|read":              {"get"},
		"PayableOpeningBalanceDetails|read":     {"get"},
		"PayableSummaryReport|read":             {"get"},
		"PaymentMode|read":                      {"get", "list", "listAll"},
		"PaymentsMade|read":                     {"get"},
		"PaymentsReceived|read":                 {"get"},
		"Product|read":                          {"get", "listAll", "paginate"},
		"ProductCategory|read":                  {"get", "list", "listAll", "paginate"},
		"ProductGroup|read":                     {"get", "paginate"},
		"ProductModifier|read":                  {"get", "list", "listAll", "paginate"},
		"ProductSalesReport|read":               {"get"},
		"ProductTransactions|read":              {"get"},
		"ProductUnit|read":                      {"get", "list", "listAll", "paginate"},
		"ProductVariant|read":                   {"get", "listAll", "paginate"},
		"ProfitAndLossReport|read":              {"get"},
		"PurchaseOrder|read":                    {"get", "paginate"},
		"PurchaseOrderDetailReport|read":        {"get"},
		"PurchasesByProductReport|read":         {"get"},
		"PurchasesBySupplierReport|read":        {"get"},
		"RealisedExchangeGainLossReport|read":   {"get"},
		"Reason|read":                           {"get", "listAll"},
		"ReceivableDetailReport|read":           {"get"},
		"ReceivableOpeningBalanceDetails|read":  {"get"},
		"ReceivableSummaryReport|read":          {"get"},
		"RecurringBill|read":                    {"get", "paginate"},
		"Role|read":                             {"get", "list"},
		"RoleModule|read":                       {"list"},
		"SalesByCustomerReport|read":            {"get"},
		"SalesByProductReport|read":             {"get"},
		"SalesBySalesPersonReport|read":         {"get"},
		"SalesInvoice|read":                     {"get", "paginate"},
		"SalesInvoiceDetailReport|read":         {"get"},
		"SalesOrder|read":                       {"get", "paginate"},
		"SalesOrderDetailReport|read":           {"get"},
		"SalesPerson|read":                      {"get", "list", "listAll", "paginate"},
		"ShipmentPreference|read":               {"get", "listAll"},
		"State|read":                            {"get", "list", "listAll", "paginate"},
		"StockSummaryReport|read":               {"get"},
		"Supplier|read":                         {"get", "paginate"},
		"SupplierBalanceSummaryReport|read":     {"get"},
		"SupplierBalancesReport|read":           {"get"},
		"SupplierCredit|read":                   {"get", "paginate"},
		"SupplierCreditDetailsReport|read":      {"get"},
		"SupplierPayment|read":                  {"get", "paginate"},
		"SupplierRefundHistoryReport|read":      {"get"},
		"Tax|read":                              {"get", "list", "listAll"},
		"TaxGroup|read":                         {"get", "list", "listAll"},
		"TopExpense|read":                       {"get"},
		"TotalCashFlow|read":                    {"get"},
		"TotalIncomeExpense|read":               {"get"},
		"TotalPayableReceivable|read":           {"get"},
		"Township|read":                         {"get", "list", "listAll", "paginate"},
		"TransactionLockingRecord|read":         {"list"},
		"TransactionNumberSeries|read":          {"get", "list"},
		"TransferOrder|read":                    {"get", "paginate"},
		"TrialBalanceReport|read":               {"get"},
		"UnrealisedExchangeGainLossReport|read": {"get"},
		"UnusedCustomerCreditAdvances|read":     {"get"},
		"UnusedCustomerCredits|read":            {"get"},
		"UnusedSupplierCreditAdvances|read":     {"get"},
		"UnusedSupplierCredits|read":            {"get"},
		"User|read":                             {"get"},
		"UserAccount|read":                      {"get", "list"},
		"Warehouse|read":                        {"get", "list", "listAll"},
		"WarehouseInventoryReport|read":         {"get"},

		"Image|upload":      {"uploadSingle", "uploadMultiple"},
		"Image|remove":      {"removeSingle"},
		"Attachment|upload": {"create"},
		"Attachment|remove": {"delete"},

		"Account|update":                 {"toggleActive", "update"},
		"BankingTransaction|update":      {"update"},
		"Bill|update":                    {"confirm", "update", "void"},
		"Branch|update":                  {"toggleActive", "update"},
		"Business|update":                {"toggleActive", "update"},
		"CreditNote|update":              {"open", "update", "void"},
		"Currency|update":                {"toggleActive", "update"},
		"Customer|update":                {"toggleActive", "update"},
		"CustomerPayment|update":         {"update"},
		"DeliveryMethod|update":          {"toggleActive", "update"},
		"Expense|update":                 {"update"},
		"Journal|update":                 {"update"},
		"Module|update":                  {"update"},
		"MoneyAccount|update":            {"toggleActive", "update"},
		"OpeningBalance|update":          {"update"},
		"PaymentMode|update":             {"toggleActive", "update"},
		"Product|create":                 {"import", "create"},
		"Product|update":                 {"toggleActive", "update"},
		"ProductCategory|update":         {"toggleActive", "update"},
		"ProductGroup|update":            {"toggleActive", "update"},
		"ProductModifier|update":         {"toggleActive", "update"},
		"ProductUnit|update":             {"toggleActive", "update"},
		"ProductVariant|update":          {"toggleActive", "update"},
		"PurchaseOrder|update":           {"cancel", "confirm", "update"},
		"Reason|update":                  {"toggleActive", "update"},
		"RecurringBill|update":           {"update"},
		"Refund|update":                  {"update"},
		"Role|update":                    {"update"},
		"RoleModule|update":              {"save"},
		"SalesInvoice|update":            {"cancelWriteOff", "confirm", "update", "void", "writeOff"},
		"SalesOrder|update":              {"cancel", "confirm", "update"},
		"SalesPerson|update":             {"toggleActive", "update"},
		"ShipmentPreference|update":      {"toggleActive", "update"},
		"State|update":                   {"toggleActive", "update"},
		"Supplier|update":                {"toggleActive", "update"},
		"SupplierCredit|update":          {"confirm", "update", "void"},
		"SupplierPayment|update":         {"update"},
		"Tax|update":                     {"toggleActive", "update"},
		"TaxGroup|update":                {"toggleActive", "update"},
		"TaxSetting|update":              {"update"},
		"Township|update":                {"toggleActive", "update"},
		"TransactionLocking|update":      {"update"},
		"TransactionNumberSeries|update": {"update"},
		"UserAccount|update":             {"toggleActive", "update"},
		"Warehouse|update":               {"toggleActive", "update"},
	}
}

func GetTransactionNumberSeriesDefault() *NewTransactionNumberSeries {
	series := &NewTransactionNumberSeries{
		Name: "Default Transaction Series",
		Modules: []NewTransactionNumberSeriesModule{
			{
				ModuleName: "Sales Order",
				Prefix:     "SO-",
			},
			{
				ModuleName: "Invoice",
				Prefix:     "IV-",
			},
			{
				ModuleName: "Customer Payment",
				Prefix:     "CP-",
			},
			{
				ModuleName: "Credit Note",
				Prefix:     "CN-",
			},
			{
				ModuleName: "Expense",
				Prefix:     "EP-",
			},
			{
				ModuleName: "Purchase Order",
				Prefix:     "PO-",
			},
			{
				ModuleName: "Bill",
				Prefix:     "BL-",
			},
			{
				ModuleName: "Supplier Payment",
				Prefix:     "SP-",
			},
			{
				ModuleName: "Supplier Credit",
				Prefix:     "SC-",
			},
			{
				ModuleName: "Manual Journal",
				Prefix:     "JN-",
			},
			{
				ModuleName: "Expense",
				Prefix:     "EX-",
			},
		},
	}

	return series
}

func GetDefaultChartOfAccounts() []NewSystemAccount {
	chartOfAccounts := []NewSystemAccount{
		{
			Name:              "Other Charges",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "Miscellaneous charges like adjustments made to the invoice can be recorded in this account.",
			SystemDefaultCode: AccountCodeOtherCharges,
		},
		{
			Name:              "Lodging",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "Any expense related to putting up at motels etc while on business travel can be entered here.",
			SystemDefaultCode: AccountCodeLodging,
		},
		{
			Name:              "Undeposited Funds",
			DetailType:        AccountDetailTypeCash,
			MainType:          AccountMainTypeAsset,
			Description:       "Record funds received by your company yet to be deposited in a bank as undeposited funds and group them as a current asset in your balance sheet.",
			SystemDefaultCode: AccountCodeUndepositedFunds,
		},
		{
			Name:              "Petty Cash",
			DetailType:        AccountDetailTypeCash,
			MainType:          AccountMainTypeAsset,
			Description:       "It is a small amount of cash that is used to pay your minor or casual expenses rather than writing a check.",
			SystemDefaultCode: AccountCodePettyCash,
		},
		{
			Name:              "Accounts Receivable",
			DetailType:        AccountDetailTypeAccountsReceivable,
			MainType:          AccountMainTypeAsset,
			Description:       "The money that customers owe you becomes the accounts receivable. A good example of this is a payment expected from an invoice sent to your customer.",
			SystemDefaultCode: AccountCodeAccountsReceivable,
		},
		{
			Name:              "Furniture and Equipment",
			DetailType:        AccountDetailTypeFixedAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "Purchases of furniture and equipment for your office that can be used for a long period of time usually exceeding one year can be tracked with this account.",
			SystemDefaultCode: AccountCodeFunitureAndEquipment,
		},
		{
			Name:              "Advance Tax",
			DetailType:        AccountDetailTypeOtherCurrentAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "Any tax which is paid in advance is recorded into the advance tax account. This advance tax payment could be a quarterly, half yearly or yearly payment.",
			SystemDefaultCode: AccountCodeAdvanceTax,
		},
		{
			Name:              "Advance Payment",
			DetailType:        AccountDetailTypeOtherCurrentAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "A current account that reports amounts paid in advance of receiving goods or services. When the goods or services are received, this account balance is decreased and an expense account is increased.",
			SystemDefaultCode: AccountCodeAdvancePayment,
		},
		{
			Name:              "Accounts Payable",
			DetailType:        AccountDetailTypeAccountsPayable,
			MainType:          AccountMainTypeLiability,
			Description:       "This is an account of all the money which you owe to others like a pending bill payment to a vendor,etc.",
			SystemDefaultCode: AccountCodeAccountsPayable,
		},
		{
			Name:              "Tax Payable",
			DetailType:        AccountDetailTypeOtherCurrentLiability,
			MainType:          AccountMainTypeLiability,
			Description:       "The amount of money which you owe to your tax authority is recorded under the tax payable account. This amount is a sum of your outstanding in taxes and the tax charged on sales.",
			SystemDefaultCode: AccountCodeTaxPayable,
		},
		{
			Name:              "Retained Earnings",
			DetailType:        AccountDetailTypeEquity,
			MainType:          AccountMainTypeEquity,
			Description:       "The earnings of your company which are not distributed among the share holders is accounted as retained earnings.",
			SystemDefaultCode: AccountCodeRetainedEarnings,
		},
		{
			Name:              "Owner's Equity",
			DetailType:        AccountDetailTypeEquity,
			MainType:          AccountMainTypeEquity,
			Description:       "The owners rights to the assets of a company can be quantified in the owner''s equity account.",
			SystemDefaultCode: AccountCodeOwnerEquity,
		},
		{
			Name:              "Opening Balance Offset",
			DetailType:        AccountDetailTypeEquity,
			MainType:          AccountMainTypeEquity,
			Description:       "This is an account where you can record the balance from your previous years earning or the amount set aside for some activities. It is like a buffer account for your funds.",
			SystemDefaultCode: AccountCodeOpeningBalanceOffset,
		},
		{
			Name:              "Sales",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "The income from the sales in your business is recorded under the sales account.",
			SystemDefaultCode: AccountCodeSales,
		},
		{
			Name:              "General Income",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "A general category of account where you can record any income which cannot be recorded into any other category.",
			SystemDefaultCode: AccountCodeGeneralIncome,
		},
		{
			Name:              "Unearned Revenue",
			DetailType:        AccountDetailTypeOtherCurrentLiability,
			MainType:          AccountMainTypeLiability,
			Description:       "A liability account that reports amounts received in advance of providing goods or services. When the goods or services are provided, this account balance is decreased and a revenue account is increased.",
			SystemDefaultCode: AccountCodeUnearnedRevenue,
		},
		{
			Name:              "Interest Income",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "A percentage of your balances and deposits are given as interest to you by your banks and financial institutions. This interest is recorded into the interest income account.",
			SystemDefaultCode: AccountCodeInterestIncome,
		},
		{
			Name:              "Late Fee Income",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "Any late fee income is recorded into the late fee income account. The late fee is levied when the payment for an invoice is not received by the due date.",
			SystemDefaultCode: AccountCodeLateFeeIncome,
		},
		{
			Name:              "Discount",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "Any reduction on your selling price as a discount can be recorded into the discount account.",
			SystemDefaultCode: AccountCodeDiscount,
		},
		{
			Name:              "Bank Fees and Charges",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "Any bank fees levied is recorded into the bank fees and charges account. A bank account maintenance fee, transaction charges, a late payment fee are some examples.",
			SystemDefaultCode: AccountCodeBankFeesAndCharges,
		},
		{
			Name:              "Exchange Gain or Loss",
			DetailType:        AccountDetailTypeOtherExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "Changing the conversion rate can result in a gain or a loss. You can record this into the exchange gain or loss account.",
			SystemDefaultCode: AccountCodeExchangeGainOrLoss,
		},
		{
			Name:              "Shipping Charge",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "Shipping charges made to the invoice will be recorded in this account.",
			SystemDefaultCode: AccountCodeShippingCharge,
		},
		{
			Name:              "Bad Debt",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "Any amount which is lost and is unrecoverable is recorded into the bad debt account.",
			SystemDefaultCode: AccountCodeBadDebt,
		},
		{
			Name:              "Opening Balance Adjustments",
			DetailType:        AccountDetailTypeOtherCurrentLiability,
			MainType:          AccountMainTypeLiability,
			Description:       "This account will hold the difference in the debits and credits entered during the opening balance.",
			SystemDefaultCode: AccountCodeOpeningBalanceAdjustments,
		},
		{
			Name:              "Employee Advance",
			DetailType:        AccountDetailTypeOtherCurrentAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "Money paid out to an employee in advance can be tracked here till it's repaid or shown to be spent for company purposes.",
			SystemDefaultCode: AccountCodeEmployeeAdvance,
		},
		{
			Name:              "Employee Reimbursements",
			DetailType:        AccountDetailTypeOtherCurrentLiability,
			MainType:          AccountMainTypeLiability,
			Description:       "This account can be used to track the reimbursements that are due to be paid out to employees.",
			SystemDefaultCode: AccountCodeEmployeeReimbursements,
		},
		{
			Name:              "Uncategorized",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "This account can be used to temporarily track expenses that are yet to be identified and classified into a particular category",
			SystemDefaultCode: AccountCodeUncategorized,
		},
		{
			Name:              "Dimension Adjustments",
			DetailType:        AccountDetailTypeOtherLiability,
			MainType:          AccountMainTypeLiability,
			Description:       "This adjustment account tracks the transfers between different dimensions like tags, branches.",
			SystemDefaultCode: AccountCodeDimensionAdjustments,
		},
		{
			Name:              "Other Expenses",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "Any minor expense on activities unrelated to primary business operations is recorded under the other expense account.",
			SystemDefaultCode: AccountCodeOtherExpenses,
		},
		{
			Name:              "Inventory Asset",
			DetailType:        AccountDetailTypeStock,
			MainType:          AccountMainTypeAsset,
			Description:       "An account which tracks the value of goods in your inventory.",
			SystemDefaultCode: AccountCodeInventoryAsset,
		},
		{
			Name:              "Cost of Goods Sold",
			DetailType:        AccountDetailTypeCostOfGoodsSold,
			MainType:          AccountMainTypeExpense,
			Description:       "An expense account which tracks the value of the goods sold.",
			SystemDefaultCode: AccountCodeCostOfGoodsSold,
		},
		{
			Name:              "Goods In Transfer",
			DetailType:        AccountDetailTypeOtherCurrentAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "An account which tracks the value of inventory transfer.",
			SystemDefaultCode: AccountCodeGoodsInTransfer,
		},
		{
			Name:              "Drawings",
			DetailType:        AccountDetailTypeEquity,
			MainType:          AccountMainTypeEquity,
			Description:       "The money withdrawn from a business by its owner can be tracked with this account.",
			SystemDefaultCode: AccountCodeDrawings,
		},
		{
			Name:              "Purchase Discounts",
			DetailType:        AccountDetailTypeIncome,
			MainType:          AccountMainTypeIncome,
			Description:       "Tracks any reduction that your vendor offers on your purchases. Some vendors also provide them to encourage quick payment settlement.",
			SystemDefaultCode: AccountCodePurchaseDiscount,
		},
		{
			Name:              "Sales to Customers (Cash)",
			DetailType:        AccountDetailTypeOtherCurrentAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "",
			SystemDefaultCode: AccountCodeSalesToCustomer,
		},
		{
			Name:              "Goods In Transit",
			DetailType:        AccountDetailTypeOtherCurrentAsset,
			MainType:          AccountMainTypeAsset,
			Description:       "An account which tracks your In Transit goods value.",
			SystemDefaultCode: AccountCodeGoodsInTransit,
		},
		{
			Name:              "Inter Branch Account",
			DetailType:        AccountDetailTypeOtherCurrentLiability,
			MainType:          AccountMainTypeLiability,
			Description:       "",
			SystemDefaultCode: AccountCodeInterBranchAccount,
		},
		{
			Name:              "Parking",
			DetailType:        AccountDetailTypeExpense,
			MainType:          AccountMainTypeExpense,
			Description:       "The parking fares you pay while on business trips can be recorded under this expense category.",
			SystemDefaultCode: AccountCodeParking,
		},
		{
			Name:              "Work In Progress",
			DetailType:        AccountDetailTypeStock,
			MainType:          AccountMainTypeAsset,
			Description:       "An account which tracks the value of goods that are currently fed into production.",
			SystemDefaultCode: AccountCodeWorkInProgress,
		},
		{
			Name:              "Finished Goods",
			DetailType:        AccountDetailTypeStock,
			MainType:          AccountMainTypeAsset,
			Description:       "An account which tracks the value of finished goods.",
			SystemDefaultCode: AccountCodeFinishedGoods,
		},

		// Add more default accounts as needed  Accounts Receivable //Accounts Payable
	}
	return chartOfAccounts
}
